//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSL.AdminPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long Id { get; set; }
        public string Oid { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool Admin { get; set; }
        public string Status { get; set; }
        public string Organization_Name { get; set; }
        public string Organization_Address_Line1 { get; set; }
        public string Organization_Address_Line2 { get; set; }
        public string Organization_City { get; set; }
        public string Organization_State { get; set; }
        public string Organization_PostalCode { get; set; }
        public string Organization_Country { get; set; }
        public bool Verified { get; set; }
        public string Phone_GUID { get; set; }
        public string Phone_Number { get; set; }
        public string Person_Name { get; set; }
        public System.Data.Entity.Spatial.DbGeography Geolocation { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<decimal> Long { get; set; }
        public bool Recipient { get; set; }
    }
}
